= Odio
:toc:
:toclevels: 1


A Python library for the input / output of
http://en.wikipedia.org/wiki/OpenDocument[ODF] documents.
 
Odio runs on Python 2.7 and 3.4 on both CPython and PyPy and supports ODF 1.1
and 1.2.

See the https://github.com/tlocke/odio[GitHub repository] for code, bugs,
feature requests etc.


== Installation

It's a good idea to set up a virtualenv:

 virtualenv venv
 . venv/bin/activate

then install Odio with pip:

 pip install odio


== Quickstart

Create a spreadsheet:

....
>>> import odio
>>> import datetime
>>> 
>>>
>>> # Create the spreadsheet. The ODF version string can be '1.2' or '1.1'
>>> with odio.create_spreadsheet(open('test.ods', "wb"), '1.2') as sheet:
...	
...	# Add a table (tab) to the spreadsheet
... 	table = sheet.append_table('Plan')
...	
...	# Add a row to  the table
...     row = [
...         "veni, vidi, vici", 0.3, 5, datetime.datetime(2015, 6, 30, 16, 38)]
...     table.append_row(row)

....

Parse a spreadsheet:

....
>>> import odio
>>>
>>>
>>> # Open the spreadsheet we just created. Can be ODF 1.1 or 1.2 format.
>>> sheet = odio.parse_spreadsheet(open('test.ods', "rb"))
>>> table = sheet.tables[0]
>>> print(table.name)
Plan
>>> for row in table.rows:
...     print(row)
['veni, vidi, vici', 0.3, 5.0, datetime.datetime(2015, 6, 30, 16, 38)]

....


== Release Notes


=== Version 0.0.7, 2015-07-17

- Can now read ODS spreadsheets. See Quickstart section for details.
- The `append_row()` method now accepts a single sequence type, rather than an
  arbitrary number of positional parameters.
- API changed so that only the top level `odio` package needs to be
  imported. The `create_spreadsheet()` function is new, and accepts an ODF
  version string ('1.1', '1.2').


=== Version 0.0.5, 2015-06-13

- Fixed links on readme file.


=== Version 0.0.4, 2015-06-13

- Renamed OdsOut to Spreadsheet to make things more intuitive.


=== Version 0.0.3, 2015-06-13

- Added support for ODF 1.2.


=== Version 0.0.1, 2015-05-25

- Make wheel setting 'universal'.


=== Version 0.0.0, 2015-05-25

- Initial release, nothing to see yet.
