= Odio
:toc:
:toclevels: 1


A Python library for the input / output of
http://en.wikipedia.org/wiki/OpenDocument[ODF] documents.
 
Odio runs on Python 2.7 and 3.4 on both CPython and PyPy and supports ODF 1.1
and 1.2.

See the https://github.com/tlocke/odio[GitHub repository] for code, bugs,
feature requests etc.


== Installation

It's a good idea to set up a virtualenv:

 virtualenv venv
 . venv/bin/activate

then install Odio with pip:

 pip install odio


== Quickstart

Create an ODF 1.1 spreadsheet...

....
>>> import odio.v1_1
>>> import datetime
>>>
>>> # Create the spreadsheet
>>> with odio.v1_1.Spreadsheet(open('test.ods', "wb")) as sheet:
...	
...	# Add a table (tab) to the spreadsheet
... 	table = sheet.append_table('Plan')
...	
...	# Add a row to  the table
...     table.append_row(
...         "veni, vidi, vici", 0.3, 5, datetime.datetime(2015, 6, 30, 16, 38))

....

Create an ODF 1.2 spreadsheet...

....
>>> import odio.v1_2
>>> import datetime
>>>
>>> # Create the spreadsheet
>>> with odio.v1_2.Spreadsheet(open('test.ods', "wb")) as sheet:
...	
...	# Add a table (tab) to the spreadsheet
... 	table = sheet.append_table('Plan')
...	
...	# Add a row to  the table
...     table.append_row(
...         "veni, vidi, vici", 0.3, 5, datetime.datetime(2015, 6, 30, 16, 38))

....


== Release Notes


=== Version 0.0.5, 2015-06-13

- Fixed links on readme file.


=== Version 0.0.4, 2015-06-13

- Renamed OdsOut to Spreadsheet to make things more intuitive.


=== Version 0.0.3, 2015-06-13

- Added support for ODF 1.2.


=== Version 0.0.1, 2015-05-25

- Make wheel setting 'universal'.


=== Version 0.0.0, 2015-05-25

- Initial release, nothing to see yet.
